
%%  使用vs code擴充套件 <mermaid>
%%  mermaid 官方文件
%%  https://mermaid.js.org/config/theming.html#theme-variables

%%{init: {'theme':'forest'}}%%

gantt
    title (專題製作-人員存活表)
    dateFormat  YYYY-MM-DD
    % 註解：此為假設性調整，需依實際情況修改

section 專題組員
    怡萍(第一任隊長) :done, 2025-05-02, 2025-05-09 
    湘筠               :done, 2025-05-02, 2025-05-19
    珮雯(第二任隊長)    :2025-05-02, 2025-05-31
    詩雲                :2025-05-02, 2025-05-31
    育宸                :2025-05-02, 2025-05-31
    士繽                :2025-05-02, 2025-05-31
    陳瑋                :2025-05-23, 2025-05-31

